 name: Build Android App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload Files
        uses: actions/upload-artifact@v4
        with:
          name: app-files
          path: .
